# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChallengeWebmotors' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'AlamofireObjectMapper'
  pod 'ObjectMapper', '~> 3.5.1'
  #pod 'R.swift', '~> 5.0.3'

  # Pods for ChallengeWebmotors

  target 'ChallengeWebmotorsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChallengeWebmotorsUITests' do
    # Pods for testing
  end

end
